# Generated by Django 2.0.2 on 2020-05-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='pic',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='这里写简介', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='desription',
            field=models.CharField(default='作品的描述', max_length=100),
        ),
    ]
