# Generated by Django 2.0.2 on 2020-05-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200526_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='desription',
            new_name='description',
        ),
    ]
